apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-gateway"
spec:
  replicas: 1            
  selector:
    matchLabels:
      service: "{{ .Release.Name }}-gateway"
  template:
    metadata:
      labels:
        service: "{{ .Release.Name }}-gateway"
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.gateway.image }}"
        imagePullPolicy: Never
        ports:
        - containerPort: 80   
        env:
        - name: PORT
          value: "80"
        - name: PROFILE_SERVICE_DOMAIN_NAME
          value: "{{ .Release.Name }}-profile.{{ .Release.Namespace }}.svc.cluster.local"

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-gateway"
spec:
  type: NodePort
  selector:
    service: "{{ .Release.Name }}-gateway"
  ports:
    - port: 80
      nodePort: 30007
